language: node_js
before_install: gem install sass
before_script:
- npm install grunt-cli -g
script: grunt
deploy:
  provider: releases
  api_key:
    secure: U9ZZ2B8PnP3d9A8iQZUoAxeI2pQV2jl+6S/Q3pxY7EioTjPCV+9W+FRuMcWY1yMx94ljxrQeca7E9fYgu16Ko74igXZa64U6czttIhX9vyFLkJS7lnuW7cZLBIlYfTvixD4khOc6+YQHv6bzpSDg9Se3WrbozCvdhG+VAIryhKppqGTRQED4YWNZtZX9i6FHGSxOfkw0s7Qxr1wmsUUCQnaquuasshoUw1h8NhDNuXvqKeS88QF4PXy6nXnhuR2lSI/kWDtCTEAGJYMWyFGFuPJAiTmgWpAPNvZMzmh55MQnnShc6CcJs1O5qq05RKSmy446yKGd4cHNw30c8zCzaU1QJ5HADkyFNRHjpxiSVLrcbVyF1Fx3ZSTpq51btFhFojuFyNmfACNuiRvbr3z0pAQ3S09A7b0DVfOdqzXQTQ2VQZLR6QOzhm9zLtW7hx+bzpKPwCCPlFnynyCb3yu5aVY3ctGwSRb9AVJHzS8nircCr8w/JnxSEfZI1XnOm5BFWr95an/Hk2iR6YL/le8MFdZpkEcZM9CiXnOZZWtrNZE1hkXgQ74Wgkcrxzm+qw6jbXiarngiatAc681wg7eE0DlLA6posbCNCjnJbTLQfiUJdnCnnweTWdk0nAxO4tosR1uOXT7fBqUhCll5m9UUratFea5Y601WTy/v+BIFhfQ=
  file: build/sempress.zip
  skip_cleanup: true
  on:
    tags: true

